### ISSUE TITLE
Calculate models for all combinations of covariates

### ISSUE THREAD

**Issue by hp2500** [masurp/specr#21]
Hi there, 

I am trying to run specifications for all possible **combinations** of covariates. Currently I only get specifications for each individual covariate and then an additional one that has all covariates. I would like to look at all possible **subsets** as well. 

As a workaround, I have generated all combinations and pasted them into model formula strings using helper code I wrote myself (e.g.: 'cov1 + cov2 + cov3', 'cov1 + cov2', 'cov1 + cov2', etc.). When passing this to the covariates arguments it seems to calculate the respective models. However, there are two issues: 1) It crashes once I use a high number of model specifications (e.g. >4000). 2) In the plot it doesn't correctly show which covariates were used. Instead, it always just colors the "all_covariates" option. 

e.g. 
```r
covariates <- c("airport_dist", "conservative", 'male', 'age', 'popdens',
                'manufact', 'tourism', 'academics', 'medinc', 'healthcare',
                'y_centroid_county', 'evanrate')


spec_results <- run_specs(df = df_us_slope_prev, 
                     y = c("onset_prev"), 
                     x = c("pers_e"), 
                     model = c("lm"), 
                     controls = covariates)

dim(spec_results)
``` 
gives me dimensions of 14x12 but it shoould be 4095x12 if all combinations were considered.

Guidance would be greatly appreciated!

**Comment by masurp** [comment]
Hi,

we intentionally decided to only include these three options (none, all, each individually) per default as we believe that the multiverse of results can otherwise be too overwhelming and less informative. A lot of these combination are almost the same and hardly tell a separate story. 

That being said, the development version of specr added a new argument to the run_specs() function which allows to compute all combinations. Simply, install the dev version from this github page, add `all.combs = TRUE` to the function and you will get the desired results. 

Best,
Philipp

**Comment by hp2500** [comment]
Excellent hint, thanks a lot!
