### ISSUE TITLE
Categorical independet variable

### ISSUE THREAD

**Issue by dfatori** [masurp/specr#34]
Not sure if this is truly an issue or just a limitation. I can't seem to run a specr analysis with independent variables that are categorical. Tried using as.factor and as.character, none works. I tried two different datasets to be sure. Is it a limitation or am I missing something?

**Comment by masurp** [comment]
Hi,

First, see this issue #33 and my related comment.

Second, the problem is that specr automatically extracts ONE coefficient resulting from the prediction of whatever variable is included as independent variable and whatever variable is included as a dependent variable. As such, including a factor would not work automatically as a factor splits the independent variable into several dummy-coded variables, resulting in several coefficients. Specr would not now which one to choose as none of them correspondings to the original variable name. 

The only meaningful work-around would be to dummy-code the factor variable yourself and then add all dummies as independent variables and covariates. By adding `simplify = FALSE` to the `setup()` function, you compute all combinations. You have to filter non meaningful specifications afterwards, but will get the right estimates. Again, see #33.

**Comment by dfatori** [comment]
Hi @masurp, I see, makes sense now. Thank you for the suggestions.
