### ISSUE TITLE
Interactions question

### ISSUE THREAD

**Issue by apolussa** [masurp/specr#36]
Hello,

Incredible tool -- thank you very much. 

A question about interactions. I am having trouble with specifying an interaction of a control with an x variable. If I include the "x_var:control1" in the controls specification, it removes either that specific x_var or the specific controls (even the non-interactive "control1"). It looks like I can include it in the add to formula, but then it includes it across all specifications. Is there some way to specify this in the specs()?

Thank you. If this is not clear, I can make try to make a reproducible example.

**Comment by masurp** [comment]
It is clear to me. The issue is the following:

In a specification curve framework, you want to estimate the relationship between two variables (not three). If you want to investigate the role of a moderator, you are most likely looking for the conditional effects of x on y contingent on z (the moderator). You want those conditional effects to show up as individual specifications in your specification plot. 

Hence, the solution is not to include an interaction term, but rather to use your moderator as a potential grouping variable that can be treated as a subset in the specr setup. This way, you will get the conditional effects as distinct specifications (see how "gender" is included in the specifications in the example analyses on the website). 

This obviously works best if the moderator is binary or nominal with few levels. In case of contious moderators, I would suggest to use a pick-a-point approach and e.g., use low, medium, and high levels. 

Does this make sense?

**Comment by apolussa** [comment]
Thank you for the quick reply- that is clear and very helpful!
